---
repos:
  - hooks:
      - id: actionlint
    repo: https://github.com/rhysd/actionlint
    rev: v1.7.4
  - hooks:
      - id: shellcheck
    repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
  - hooks:
      - id: yamllint
    repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
