---
description: >
  Bump semantic version automatically when changes are committed
  to the default branch.
inputs:
  create_component_tags:
    default: "true"
    description: >
      Create Git tags with version components.  For example, `v1.2.3` will
      create `v1`, `v1.2`, and `v1.2.3` tags and will replace any existing
      tags with those names.
  dry_run:
    default: "false"
    description: Run semantic-release in dry run mode.
    required: false
  github_token:
    description: "GitHub token associated with the calling repository."
    required: true
name: Semantic Version
outputs:
  release-version:
    description: Release Version
    value: ${{ steps.release.outputs.version }}
runs:
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        if [[ -z "${{ inputs.github_token }}" ]]; then
          echo "::error::Missing required input: github_token"
          exit 1
        fi
        echo "✅ Inputs Validated" >> $GITHUB_STEP_SUMMARY
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: >
          ${{
            github.event_name == 'pull_request' && github.head_ref || github.ref_name
          }}
    - name: Remove Package.json files
      shell: bash
      run: |
        find . -type f -name 'package.json' | xargs rm -f
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      id: release
      name: Release
      shell: bash
      run: |
        echo "🚀 Running Semantic Version!"

        $GITHUB_ACTION_PATH/semantic-version.sh \
        ${{ inputs.dry_run == 'false' && ' ' || '-d' }} \
        ${{ inputs.create_component_tags == 'true' && '-c' || '' }}
    - name: Validate Pre-Release PRs for using Semantic Notation
      if: github.event_name == 'pull_request'
      env:
        RELEASE_VERSION: ${{ steps.release.outputs.version }}
        PR_REGEX: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\(.*\))?(!)?:.*'
        PR_TITLE: ${{ github.event.pull_request.title }}
      shell: bash
      run: |
        echo "::debug::PR Title: ${PR_TITLE}"
        echo "ℹ️ PR Title: ${PR_TITLE} ">> $GITHUB_STEP_SUMMARY
        echo "ℹ️ Release Version: ${RELEASE_VERSION}" >> $GITHUB_STEP_SUMMARY

        ERRORS=false
        if [[ ! "$PR_TITLE" =~ $PR_REGEX ]]; then
          echo "❌ PR Title did not validate" >> $GITHUB_STEP_SUMMARY
          echo -e "::error::\033[1;31mPR title must follow conventional commit syntax."
          ERRORS=true
        fi
        if [[ ! -z "${RELEASE_VERSION}" ]]; then
          echo "❌ Release Version is !-z" >> $GITHUB_STEP_SUMMARY
          echo -e "::error::\033[1;31mNo commits that follow semantic notation were found."
          ERRORS=true
        fi
        if [[ $ERRORS = true ]]; then
          echo "💥 Validation of PR Check failed" >> $GITHUB_STEP_SUMMARY
          echo -e "::error::\033[1;35mBailing due to errors.\033[0m"
          exit 1
        fi
        echo "✅ Validated PR Checks" >> $GITHUB_STEP_SUMMARY
  using: composite
