---
name: Main
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
  semantic-version:
    needs:
      - pre-commit
    outputs:
      release-version: ${{ steps.semver.outputs.release-version }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: semver
        name: Semantic Version
        uses: ./
        with:
          dry_run: ${{ github.ref_name != 'main' }}
          github_token: ${{ github.token }}
  check-workflow-sync:
    needs:
      - semantic-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          VERSION: ${{ needs.semantic-version.outputs.release-version }}
        name: Check Workflow Version
        run: |
          MAJOR="${VERSION%%.*}"
          ACTION="r35krag0th/action-semantic-version"
          WF_FILE=".github/workflows/version.yml"
          WF_VERSION="$(grep "${ACTION}" "$WF_FILE" | sed 's/.*@//')"

          if [[ "$WF_VERSION" != "v${MAJOR}" ]]; then
            echo "Action version in workflow does not match version to be released."
            echo ""
            echo "Changes would release major version '$MAJOR'."
            echo "Workflow has version: '$WF_VERSION'."
            exit 1
          else
            echo "Workflow version '$WF_VERSION' matches next release major"
            echo "version '${MAJOR}'."
          fi
